/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button2;
  GtkWidget *button1;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  label1 = gtk_label_new (_("Menu"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 184, 40);
  gtk_widget_set_size_request (label1, 41, 17);

  button2 = gtk_button_new_with_mnemonic (_("reclamation restauration"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 112, 192);
  gtk_widget_set_size_request (button2, 192, 48);

  button1 = gtk_button_new_with_mnemonic (_("reclamation hebergement"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 112, 88);
  gtk_widget_set_size_request (button1, 192, 56);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");

  return acceuil;
}

GtkWidget*
create_RH (void)
{
  GtkWidget *RH;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *Modifier_RH;
  GtkWidget *button3;
  GtkWidget *Ajouter_RH;
  GtkWidget *label17;

  RH = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (RH, 800, 800);
  gtk_window_set_title (GTK_WINDOW (RH), _("reclamation hebergement"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (RH), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 16, 24);
  gtk_widget_set_size_request (treeview1, 720, 520);

  Modifier_RH = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier_RH);
  gtk_fixed_put (GTK_FIXED (fixed2), Modifier_RH, 176, 576);
  gtk_widget_set_size_request (Modifier_RH, 96, 64);

  button3 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 672, 576);
  gtk_widget_set_size_request (button3, 96, 64);

  Ajouter_RH = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (Ajouter_RH);
  gtk_fixed_put (GTK_FIXED (fixed2), Ajouter_RH, 32, 576);
  gtk_widget_set_size_request (Ajouter_RH, 96, 64);

  label17 = gtk_label_new (_("en cas ou vous verrez supprimer une reclamation : double clique sur la reclamation consern\303\251e dans votre tableau !"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 24, 664);
  gtk_widget_set_size_request (label17, 768, 96);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Modifier_RH, "clicked",
                    G_CALLBACK (on_Modifier_RH_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_RH, "clicked",
                    G_CALLBACK (on_Ajouter_RH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RH, RH, "RH");
  GLADE_HOOKUP_OBJECT (RH, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (RH, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (RH, Modifier_RH, "Modifier_RH");
  GLADE_HOOKUP_OBJECT (RH, button3, "button3");
  GLADE_HOOKUP_OBJECT (RH, Ajouter_RH, "Ajouter_RH");
  GLADE_HOOKUP_OBJECT (RH, label17, "label17");

  return RH;
}

GtkWidget*
create_RR (void)
{
  GtkWidget *RR;
  GtkWidget *fixed3;
  GtkWidget *treeview2;
  GtkWidget *Ajouter_RR;
  GtkWidget *Modifier_RR;
  GtkWidget *button4;
  GtkWidget *label18;

  RR = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (RR, 800, 800);
  gtk_window_set_title (GTK_WINDOW (RR), _("reclamation restauration"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (RR), fixed3);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview2, 16, 8);
  gtk_widget_set_size_request (treeview2, 664, 488);

  Ajouter_RR = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (Ajouter_RR);
  gtk_fixed_put (GTK_FIXED (fixed3), Ajouter_RR, 32, 528);
  gtk_widget_set_size_request (Ajouter_RR, 96, 64);

  Modifier_RR = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier_RR);
  gtk_fixed_put (GTK_FIXED (fixed3), Modifier_RR, 176, 528);
  gtk_widget_set_size_request (Modifier_RR, 96, 64);

  button4 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 624, 520);
  gtk_widget_set_size_request (button4, 96, 64);

  label18 = gtk_label_new (_("en cas ou vous verrez supprimer une reclamation : double clique sur la reclamation consern\303\251e dans votre tableau !"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 8, 704);
  gtk_widget_set_size_request (label18, 776, 40);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_RR, "clicked",
                    G_CALLBACK (on_Ajouter_RR_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier_RR, "clicked",
                    G_CALLBACK (on_Modifier_RR_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RR, RR, "RR");
  GLADE_HOOKUP_OBJECT (RR, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (RR, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (RR, Ajouter_RR, "Ajouter_RR");
  GLADE_HOOKUP_OBJECT (RR, Modifier_RR, "Modifier_RR");
  GLADE_HOOKUP_OBJECT (RR, button4, "button4");
  GLADE_HOOKUP_OBJECT (RR, label18, "label18");

  return RR;
}

GtkWidget*
create_M_RH (void)
{
  GtkWidget *M_RH;
  GtkWidget *fixed4;
  GtkWidget *label19;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *modifier_RH;
  GtkWidget *Retour_M_RH;
  GtkWidget *label24;

  M_RH = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (M_RH), _("Modifier RH"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (M_RH), fixed4);

  label19 = gtk_label_new (_("id"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 64, 56);
  gtk_widget_set_size_request (label19, 49, 17);

  label23 = gtk_label_new (_("probleme\n"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 56, 280);
  gtk_widget_set_size_request (label23, 80, 40);

  label22 = gtk_label_new (_("tel"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 64, 208);
  gtk_widget_set_size_request (label22, 49, 17);

  label21 = gtk_label_new (_("email\n"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 64, 152);
  gtk_widget_set_size_request (label21, 49, 17);

  label20 = gtk_label_new (_("nom"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 64, 104);
  gtk_widget_set_size_request (label20, 49, 17);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11, 136, 48);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 136, 96);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed4), entry13, 136, 152);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed4), entry14, 136, 208);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15, 144, 280);
  gtk_widget_set_size_request (entry15, 216, 120);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  modifier_RH = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier_RH);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier_RH, 24, 456);
  gtk_widget_set_size_request (modifier_RH, 80, 48);

  Retour_M_RH = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (Retour_M_RH);
  gtk_fixed_put (GTK_FIXED (fixed4), Retour_M_RH, 616, 488);
  gtk_widget_set_size_request (Retour_M_RH, 66, 29);

  label24 = gtk_label_new (_("votre reclamation :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 104, 456);
  gtk_widget_set_size_request (label24, 488, 48);

  g_signal_connect ((gpointer) modifier_RH, "clicked",
                    G_CALLBACK (on_modifier_RH_clicked),
                    NULL);
  g_signal_connect ((gpointer) Retour_M_RH, "clicked",
                    G_CALLBACK (on_Retour_M_RH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (M_RH, M_RH, "M_RH");
  GLADE_HOOKUP_OBJECT (M_RH, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (M_RH, label19, "label19");
  GLADE_HOOKUP_OBJECT (M_RH, label23, "label23");
  GLADE_HOOKUP_OBJECT (M_RH, label22, "label22");
  GLADE_HOOKUP_OBJECT (M_RH, label21, "label21");
  GLADE_HOOKUP_OBJECT (M_RH, label20, "label20");
  GLADE_HOOKUP_OBJECT (M_RH, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (M_RH, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (M_RH, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (M_RH, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (M_RH, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (M_RH, modifier_RH, "modifier_RH");
  GLADE_HOOKUP_OBJECT (M_RH, Retour_M_RH, "Retour_M_RH");
  GLADE_HOOKUP_OBJECT (M_RH, label24, "label24");

  return M_RH;
}

GtkWidget*
create_M_RR (void)
{
  GtkWidget *M_RR;
  GtkWidget *fixed5;
  GtkWidget *Retour_M_RR;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *label29;
  GtkWidget *modifier_RR;
  GtkWidget *label30;

  M_RR = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (M_RR), _("Modifier RR"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (M_RR), fixed5);

  Retour_M_RR = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (Retour_M_RR);
  gtk_fixed_put (GTK_FIXED (fixed5), Retour_M_RR, 648, 568);
  gtk_widget_set_size_request (Retour_M_RR, 66, 29);

  label25 = gtk_label_new (_("id"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 88, 40);
  gtk_widget_set_size_request (label25, 49, 17);

  label26 = gtk_label_new (_("nom\n"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 96, 88);
  gtk_widget_set_size_request (label26, 49, 17);

  label27 = gtk_label_new (_("email\n"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 96, 136);
  gtk_widget_set_size_request (label27, 49, 17);

  label28 = gtk_label_new (_("tel"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 96, 184);
  gtk_widget_set_size_request (label28, 49, 17);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed5), entry16, 160, 32);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed5), entry17, 160, 88);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed5), entry18, 160, 136);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed5), entry19, 160, 184);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed5), entry20, 160, 240);
  gtk_widget_set_size_request (entry20, 192, 168);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label29 = gtk_label_new (_("probleme"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 64, 232);
  gtk_widget_set_size_request (label29, 88, 40);

  modifier_RR = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier_RR);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_RR, 40, 504);
  gtk_widget_set_size_request (modifier_RR, 88, 56);

  label30 = gtk_label_new (_("votre reclamation:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 152, 504);
  gtk_widget_set_size_request (label30, 408, 56);

  g_signal_connect ((gpointer) Retour_M_RR, "clicked",
                    G_CALLBACK (on_Retour_M_RR_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_RR, "clicked",
                    G_CALLBACK (on_modifier_RR_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (M_RR, M_RR, "M_RR");
  GLADE_HOOKUP_OBJECT (M_RR, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (M_RR, Retour_M_RR, "Retour_M_RR");
  GLADE_HOOKUP_OBJECT (M_RR, label25, "label25");
  GLADE_HOOKUP_OBJECT (M_RR, label26, "label26");
  GLADE_HOOKUP_OBJECT (M_RR, label27, "label27");
  GLADE_HOOKUP_OBJECT (M_RR, label28, "label28");
  GLADE_HOOKUP_OBJECT (M_RR, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (M_RR, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (M_RR, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (M_RR, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (M_RR, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (M_RR, label29, "label29");
  GLADE_HOOKUP_OBJECT (M_RR, modifier_RR, "modifier_RR");
  GLADE_HOOKUP_OBJECT (M_RR, label30, "label30");

  return M_RR;
}

GtkWidget*
create_A_RH (void)
{
  GtkWidget *A_RH;
  GtkWidget *fixed8;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *Retour_A_RH;
  GtkWidget *reclamer_RH;

  A_RH = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (A_RH), _("Ajouter RH"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (A_RH), fixed8);

  label2 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed8), label2, 56, 56);
  gtk_widget_set_size_request (label2, 96, 48);

  label3 = gtk_label_new (_("nom"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed8), label3, 72, 136);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("email"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed8), label4, 72, 184);
  gtk_widget_set_size_request (label4, 48, 32);

  label5 = gtk_label_new (_("tel"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed8), label5, 72, 256);
  gtk_widget_set_size_request (label5, 41, 17);

  label6 = gtk_label_new (_("probleme"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed8), label6, 64, 312);
  gtk_widget_set_size_request (label6, 80, 40);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed8), entry1, 168, 64);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed8), entry2, 168, 128);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3, 168, 184);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 168, 248);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed8), entry5, 168, 312);
  gtk_widget_set_size_request (entry5, 160, 144);
  gtk_entry_set_max_length (GTK_ENTRY (entry5), 99);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  Retour_A_RH = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (Retour_A_RH);
  gtk_fixed_put (GTK_FIXED (fixed8), Retour_A_RH, 336, 496);
  gtk_widget_set_size_request (Retour_A_RH, 80, 40);

  reclamer_RH = gtk_button_new_with_mnemonic (_("Reclamer"));
  gtk_widget_show (reclamer_RH);
  gtk_fixed_put (GTK_FIXED (fixed8), reclamer_RH, 48, 496);
  gtk_widget_set_size_request (reclamer_RH, 88, 40);

  g_signal_connect ((gpointer) Retour_A_RH, "clicked",
                    G_CALLBACK (on_Retour_A_RH_clicked),
                    NULL);
  g_signal_connect ((gpointer) reclamer_RH, "clicked",
                    G_CALLBACK (on_reclamer_RH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (A_RH, A_RH, "A_RH");
  GLADE_HOOKUP_OBJECT (A_RH, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (A_RH, label2, "label2");
  GLADE_HOOKUP_OBJECT (A_RH, label3, "label3");
  GLADE_HOOKUP_OBJECT (A_RH, label4, "label4");
  GLADE_HOOKUP_OBJECT (A_RH, label5, "label5");
  GLADE_HOOKUP_OBJECT (A_RH, label6, "label6");
  GLADE_HOOKUP_OBJECT (A_RH, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (A_RH, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (A_RH, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (A_RH, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (A_RH, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (A_RH, Retour_A_RH, "Retour_A_RH");
  GLADE_HOOKUP_OBJECT (A_RH, reclamer_RH, "reclamer_RH");

  return A_RH;
}

GtkWidget*
create_A_RR (void)
{
  GtkWidget *A_RR;
  GtkWidget *fixed9;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *Retour_A_RR;
  GtkWidget *reclamer_RR;

  A_RR = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (A_RR), _("Ajouter RR"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (A_RR), fixed9);

  label9 = gtk_label_new (_("id"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed9), label9, 40, 80);
  gtk_widget_set_size_request (label9, 41, 17);

  label10 = gtk_label_new (_("nom"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed9), label10, 40, 128);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("mail"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed9), label11, 40, 184);
  gtk_widget_set_size_request (label11, 49, 17);

  label13 = gtk_label_new (_("probleme"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed9), label13, 40, 272);
  gtk_widget_set_size_request (label13, 88, 40);

  label12 = gtk_label_new (_("tel"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed9), label12, 40, 232);
  gtk_widget_set_size_request (label12, 49, 17);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed9), entry6, 152, 72);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed9), entry7, 152, 128);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed9), entry8, 152, 176);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed9), entry9, 152, 232);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed9), entry10, 152, 280);
  gtk_widget_set_size_request (entry10, 160, 200);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  Retour_A_RR = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (Retour_A_RR);
  gtk_fixed_put (GTK_FIXED (fixed9), Retour_A_RR, 296, 552);
  gtk_widget_set_size_request (Retour_A_RR, 74, 29);

  reclamer_RR = gtk_button_new_with_mnemonic (_("Reclamer"));
  gtk_widget_show (reclamer_RR);
  gtk_fixed_put (GTK_FIXED (fixed9), reclamer_RR, 48, 552);
  gtk_widget_set_size_request (reclamer_RR, 80, 48);

  g_signal_connect ((gpointer) Retour_A_RR, "clicked",
                    G_CALLBACK (on_Retour_A_RR_clicked),
                    NULL);
  g_signal_connect ((gpointer) reclamer_RR, "clicked",
                    G_CALLBACK (on_reclamer_RR_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (A_RR, A_RR, "A_RR");
  GLADE_HOOKUP_OBJECT (A_RR, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (A_RR, label9, "label9");
  GLADE_HOOKUP_OBJECT (A_RR, label10, "label10");
  GLADE_HOOKUP_OBJECT (A_RR, label11, "label11");
  GLADE_HOOKUP_OBJECT (A_RR, label13, "label13");
  GLADE_HOOKUP_OBJECT (A_RR, label12, "label12");
  GLADE_HOOKUP_OBJECT (A_RR, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (A_RR, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (A_RR, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (A_RR, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (A_RR, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (A_RR, Retour_A_RR, "Retour_A_RR");
  GLADE_HOOKUP_OBJECT (A_RR, reclamer_RR, "reclamer_RR");

  return A_RR;
}

GtkWidget*
create_f_OKH (void)
{
  GtkWidget *f_OKH;
  GtkWidget *fixed10;
  GtkWidget *label7;
  GtkWidget *OKH;

  f_OKH = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (f_OKH), _("sucess"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (f_OKH), fixed10);

  label7 = gtk_label_new (_("operation effectu\303\251 !"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed10), label7, 104, 48);
  gtk_widget_set_size_request (label7, 184, 56);

  OKH = gtk_button_new_with_mnemonic (_("OK !"));
  gtk_widget_show (OKH);
  gtk_fixed_put (GTK_FIXED (fixed10), OKH, 136, 184);
  gtk_widget_set_size_request (OKH, 112, 64);

  g_signal_connect ((gpointer) OKH, "clicked",
                    G_CALLBACK (on_OKH_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (f_OKH, f_OKH, "f_OKH");
  GLADE_HOOKUP_OBJECT (f_OKH, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (f_OKH, label7, "label7");
  GLADE_HOOKUP_OBJECT (f_OKH, OKH, "OKH");

  return f_OKH;
}

GtkWidget*
create_f_OKR (void)
{
  GtkWidget *f_OKR;
  GtkWidget *fixed11;
  GtkWidget *label8;
  GtkWidget *OKF;

  f_OKR = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (f_OKR), _("sucess"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (f_OKR), fixed11);

  label8 = gtk_label_new (_("operation effectu\303\251 !"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed11), label8, 104, 48);
  gtk_widget_set_size_request (label8, 192, 48);

  OKF = gtk_button_new_with_mnemonic (_("OK !"));
  gtk_widget_show (OKF);
  gtk_fixed_put (GTK_FIXED (fixed11), OKF, 160, 160);
  gtk_widget_set_size_request (OKF, 104, 72);

  g_signal_connect ((gpointer) OKF, "clicked",
                    G_CALLBACK (on_OKF_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (f_OKR, f_OKR, "f_OKR");
  GLADE_HOOKUP_OBJECT (f_OKR, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (f_OKR, label8, "label8");
  GLADE_HOOKUP_OBJECT (f_OKR, OKF, "OKF");

  return f_OKR;
}

