/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_RH (void);
GtkWidget* create_RR (void);
GtkWidget* create_M_RH (void);
GtkWidget* create_M_RR (void);
GtkWidget* create_A_RH (void);
GtkWidget* create_A_RR (void);
GtkWidget* create_f_OKH (void);
GtkWidget* create_f_OKR (void);
