/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_hebergement (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_rechercher (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_afficher (void);
