/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_ajout_utilisateur (void);
GtkWidget* create_affichage_et_recherche (void);
GtkWidget* create_modification (void);
