/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Acceuil (void);
GtkWidget* create_Gestion (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_Afficher (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_Recherchetr (void);
GtkWidget* create_Dashboard2 (void);
GtkWidget* create_Dashboard3 (void);
GtkWidget* create_Login_gestionstock (void);
GtkWidget* create_Login_bienvenue (void);
GtkWidget* create_Ajout_produit (void);
GtkWidget* create_Stock (void);
GtkWidget* create_Modification (void);
GtkWidget* create_rupture (void);
GtkWidget* create_confirmer_suppr (void);
GtkWidget* create_SuperAcceuil (void);
